spring:
  application:
    name: notificationservice
  data:
    mongodb:
      database: taskdb
      uri: mongodb+srv://admin:vvJlPhgzBAC2egJb@todo-app.jcre3.mongodb.net/
  mail:
    host: smtp.gmail.com
    port: 587
    username: todo3576@gmail.com
    password: tkfw ssim hnkq mykh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloud:
  aws:
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
      auto: false
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    stack:
      auto: false
    sqs:
      queue:
        TaskStatus:
          name: TaskStatus.fifo
          fifo: true
server:
  port: 8045

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true