apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  spring.mail.password: dGtmdyBzc2ltIGhua3EgbXlraA==
  cloud.aws.credentials.access-key: QUtJQVlaWkdUREZFVUc3UFlHNks=
  cloud.aws.credentials.secret-key: WWJvdDBCNjY3VXdIRkFScys2UVAwYnpxTmRhRFFrZ3lTdDNscnVEYw==
  jwt.secret: dGhpc2lzbXlzZWNyZXRrZXk=